name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set executable permissions
        run: chmod +x scripts/*.sh utils/*.sh
      
      - name: Syntax check scripts
        run: |
          bash -n scripts/backup.sh
          bash -n scripts/restore.sh
          bash -n scripts/verify.sh
          bash -n scripts/backup_databases.sh || true
      
      - name: Run shellcheck linter
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          shellcheck scripts/*.sh utils/*.sh || true
